### ISSUE TITLE
I'm not even really sure, Blender isn't my thing.

### ISSUE THREAD

**Issue by redwhat1234** [Marlamin/WoWExportTools#41]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_adt\__init__.py", line 77, in execute
    return import_adtobj.load(context, self.filepath)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_adt\import_adtobj.py", line 82, in load
    nodes = node_tree.nodes
AttributeError: 'NoneType' object has no attribute 'nodes'

**Comment by Marlamin** [comment]
Start off with a fresh Blender scene, it might be renaming the models and that piece of code counts on the name being something exact during import.
